Repository HealthScreening/HealthScreeningBot, pull requests merged in 2021-12, with the labels that each got.

#40 License change
  LICENSE
  src/client.ts
  src/client/autoAssignSchoolRole.ts
  src/client/doAutoLoop.ts
  src/client/extraClient.ts
  src/commands/deleteAuto.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/sendToAll.ts
  src/commands/setAuto.ts
  src/commands/setDevice.ts
  src/commands/stats.ts
  src/commands/stopBot.ts
  src/commands/triggerAutoNow.ts
  src/deploy.ts
  src/discordjs-overrides.d.ts
  src/orm.ts
  src/screeningClient.ts
  src/utils/hmsFromMillis.ts
  src/utils/multiMessage.ts
  src/utils/produce_screenshot.ts
  src/utils/workerQueue.ts
Labels: enhancement

#33 Utilize eslint on the codebase
  .eslintignore
  .eslintrc.json
  .github/dependabot.yml
  .github/workflows/docs.yml
  .github/workflows/main.yml
  .gitignore
  .prettierignore
  .prettierrc.json
  config.example.ts
  docs/package-lock.json
  docs/package.json
  docs/src/.vuepress/config.ts
  docs/src/.vuepress/sidebar/commands.ts
  docs/src/.vuepress/sidebar/dev/dev.ts
  docs/src/.vuepress/sidebar/dev/self-host.ts
  docs/src/.vuepress/sidebar/quickstart.ts
  docs/src/.vuepress/sidebar/server.ts
  docs/src/.vuepress/styles/index.scss
  docs/src/commands/generate-auto.md
  docs/src/commands/generate-once.md
  docs/src/commands/hsb-generate-auto.md
  docs/src/commands/send-to-all.md
  docs/src/commands/set-auto.md
  docs/src/commands/set-device.md
  docs/src/dev/self-host/configuration/index.md
  docs/src/dev/self-host/requirements.md
  docs/src/index.md
  docs/src/quickstart/invite-bot.md
  docs/src/server/fun-bots.md
  docs/src/server/rules.md
  package-lock.json
  package.json
  src/client.ts
  src/client/autoAssignSchoolRole.ts
  src/client/doAutoLoop.ts
  src/client/extraClient.ts
  src/commands/deleteAuto.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/sendToAll.ts
  src/commands/setAuto.ts
  src/commands/setDevice.ts
  src/commands/stats.ts
  src/commands/stopBot.ts
  src/commands/triggerAutoNow.ts
  src/deploy.ts
  src/discordjs-overrides.d.ts
  src/orm.ts
  src/screeningClient.ts
  src/utils/hmsFromMillis.ts
  src/utils/multiMessage.ts
  src/utils/produce_screenshot.ts
  src/utils/workerQueue.ts
  tsconfig.json
Labels: enhancement

#45 Add lint ci
  .github/workflows/lint.yml
  package.json
  src/client.ts
  src/client/autoAssignSchoolRole.ts
  src/client/doAutoLoop.ts
  src/client/extraClient.ts
  src/commands/deleteAuto.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/sendToAll.ts
  src/commands/setAuto.ts
  src/commands/setDevice.ts
  src/commands/stats.ts
  src/commands/stopBot.ts
  src/commands/triggerAutoNow.ts
  src/deploy.ts
  src/discordjs-overrides.d.ts
  src/orm.ts
  src/screeningClient.ts
  src/utils/hmsFromMillis.ts
  src/utils/multiMessage.ts
  src/utils/produce_screenshot.ts
  src/utils/workerQueue.ts
Labels: enhancement

#46 Use vscode sqlite
  package-lock.json
  package.json
Labels: enhancement, dependencies, javascript

#47 Use version 0.2.0-canary.0 for `@discordjs/rest`
  package-lock.json
  package.json
Labels: enhancement, dependencies, javascript

#58 Fix deploy bug by resolving to the base path
  package.json
  src/client/extraClient.ts
  src/deploy.ts
Labels: bug

#62 Resolve path segments first
  src/utils/produceScreenshot/getScreenshot.ts
Labels: bug

#65 Don't put file url in the resolve call
  src/utils/produceScreenshot/getScreenshot.ts
Labels: bug

#128 Add migration guide
  docs/src/dev/self-host/v1-to-v2.md
Labels: documentation

#129 Order by createdAt asc
  src/client/doAutoLoop.ts
Labels: enhancement

#130 Add indices and migrate
  src/orm/autoUser.ts
  src/orm/migrations/migrations/20211217025545-8-noname.ts
  src/orm/migrations/migrations/20211217025721-9-noname.ts
  src/orm/migrations/migrations/_current.json
  src/orm/migrations/migrations/_current_bak.json
  src/orm/migrations/models/autouser.ts
Labels: enhancement

#102 Version bump
  package.json
Labels: version change

#131 Final verison bump for 2.0.0
  package.json
Labels: enhancement

#142 Add logging for auto loop
  src/client/doAutoLoop.ts
Labels: bug

#145 Redo guild member cache
  src/client/doGuildMemberCacheUpdate.ts
  src/client/extraClient.ts
  src/utils/getValidUserIDs.ts
Labels: bug

#146 Use ArrayStringMap to make sure array access is not compromised
  package-lock.json
  package.json
  src/client/doAutoLoop.ts
Labels: bug

#148 Ignore error
  errorLogIgnore.json
  package-lock.json
  package.json
  src/utils/logError/ignoreError.ts
  src/utils/logError/index.ts
Labels: enhancement

#150 Version bump
  package.json
Labels: enhancement

#154 Bump to rc status
  package.json
Labels: enhancement

#157 Use sleep function from package instead of homegrown
  package-lock.json
  package.json
  src/client/doGuildMemberCacheUpdate.ts
  src/client/extraClient.ts
  src/commands/sendToAll.ts
  src/utils/sleep.ts
Labels: enhancement

#160 Fix import
  src/orm/migrations/models/autouser.ts
Labels: bug

#155 Add object so that import works correctly
  errorLogIgnore.json
  src/utils/logError/ignoreError.ts
Labels: bug

#161 Version bump
  package.json
Labels: version change

#163 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#165 Function to run function or log error
  src/client/extraClient.ts
  src/utils/logError/runAndLog.ts
Labels: enhancement

#167 Email only mode
  scripts/updateAutoMigration.ts
  scripts/updateAutoMigration/1-new.txt
  scripts/updateAutoMigration/1-old.txt
  scripts/updateAutoMigration/2-new.txt
  scripts/updateAutoMigration/2-old.txt
  src/client/doAutoLoop.ts
  src/client/extraClient.ts
  src/commands/error/log/view.ts
  src/commands/error/view.ts
  src/commands/setAuto.ts
  src/orm/autoUser.ts
  src/orm/errorLog.ts
  src/orm/migrations/migrations/20211219031414-10-noname.ts
  src/orm/migrations/migrations/20211219040913-11-noname.ts
  src/orm/migrations/migrations/_current.json
  src/orm/migrations/migrations/_current_bak.json
  src/orm/migrations/models/autouser.ts
  src/orm/migrations/models/errorlog.ts
  src/screeningClient/getUserInfo/getAutoData.ts
  src/screeningClient/index.ts
  src/screeningClient/interfaces.ts
  src/screeningClient/processScreening/generateAndSendScreenshot.ts
  src/screeningClient/processScreening/index.ts
  src/utils/multiMessage.ts
Labels: enhancement

#171 Move code into try block
  src/commands/setAuto.ts
Labels: bug

#176 Fix trigger auto
  src/client.ts
  src/commands/setAuto.ts
  src/commands/setCommand.ts
  src/commands/setDevice.ts
  src/commands/triggerAutoNow.ts
  src/screeningClient/processScreening/index.ts
  src/screeningClient/processScreening/logSuccess.ts
  src/utils/createOrUpdate.ts
Labels: bug, enhancement

#181 Set days
  src/commands/setCommand.ts
Labels: enhancement

#183 Ignore extra error
  errorLogIgnore.json
Labels: bug

#186 Profile
  src/commands/profile.ts
  src/utils/produceScreenshot.ts
Labels: bug, enhancement

#189 Holidays
  holidays.json
  src/client/doAutoLoop.ts
  src/commands/profile.ts
  src/commands/sendToAll.ts
  src/commands/stats.ts
  src/commands/stopBot.ts
  src/commands/testScreening.ts
  src/commands/triggerAutoNow.ts
  src/utils/getHolidays.ts
  src/utils/getValidUserIDs.ts
Labels: bug, enhancement

#190 Set second
  src/client/doAutoLoop.ts
Labels: bug

#191 Version bump
  package.json
Labels: version change

#193 Update package.json
  package.json
Labels: version change

#105 Add paginator source
  package-lock.json
  package.json
  src/utils/customCollector.ts
  src/utils/multiMessage.ts
  src/utils/paginator.ts
Labels: enhancement

#225 Make the error log have a paginator
  package.json
  src/commands/error.ts
  src/commands/error/log/view.ts
  src/utils/customCollector.ts
  src/utils/logError/serializeMessageComponentInteraction.ts
  src/utils/multiMessage.ts
  src/utils/paginator.ts
Labels: bug, enhancement

#232 Rework dependencies and version bump
  package-lock.json
  package.json
Labels: enhancement, dependencies

#206 Create CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: documentation

#217 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#261 Add Autocomplete
  package.json
  src/client.ts
  src/client/command.ts
  src/client/extraClient.ts
  src/client/interactions/commandInteraction.ts
  src/client/interactions/commandInteractionAutocomplete.ts
  src/client/interfaces.ts
  src/client/resolve.ts
  src/commands/deleteAuto.ts
  src/commands/error.ts
  src/commands/error/index.ts
  src/commands/error/log.ts
  src/commands/error/log/index.ts
  src/commands/error/log/view/autocomplete/after.ts
  src/commands/error/log/view/autocomplete/afterTime.ts
  src/commands/error/log/view/autocomplete/before.ts
  src/commands/error/log/view/autocomplete/beforeTime.ts
  src/commands/error/log/view/autocomplete/typeStartsWith.ts
  src/commands/error/log/view/index.ts
  src/commands/error/post.ts
  src/commands/error/view.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/profile.ts
  src/commands/sendToAll.ts
  src/commands/setAuto.ts
  src/commands/setCommand.ts
  src/commands/stats.ts
  src/commands/stopBot.ts
  src/commands/testScreening.ts
  src/commands/triggerAutoNow.ts
  src/deploy.ts
  src/discordjs-overrides.d.ts
  src/utils/handleCommandError.ts
  src/utils/logError/serializeInteraction.ts
  src/utils/paginator.ts
  src/utils/runSubcommands.ts
Labels: enhancement

#262 Dependency mess
  package-lock.json
  package.json
Labels: dependencies

#263 Device autocomplete
  src/commands/error/log/view/autocomplete/typeStartsWith.ts
  src/commands/error/log/view/index.ts
  src/commands/setCommand/autocomplete/devices.ts
  src/commands/setCommand/autocomplete/minute.ts
  src/commands/setCommand/index.ts
  src/utils/generateNumberChoicesInRange.ts
Labels: enhancement

#264 Add ephemeral options
  src/commands/error/log/view/index.ts
  src/commands/error/view.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/profile.ts
  src/commands/setAuto.ts
  src/commands/setCommand/index.ts
  src/commands/testScreening.ts
Labels: enhancement

#265 Skip checks
  src/commands/triggerAutoNow.ts
Labels: enhancement

#268 Update message to reflect subject
  src/commands/testScreening.ts
Labels: enhancement

#269 Log errors to console
  src/client.ts
Labels: enhancement

#270 Owner check
  src/commands/stopBot.ts
  src/commands/triggerAutoNow.ts
Labels: bug, enhancement

#271 Global buttons
  buttonPresets.json
  src/buttons/delete.ts
  src/client/extraClient.ts
  src/client/interactions/messageComponentInteraction.ts
  src/screeningClient/processScreening/generateAndSendScreenshot.ts
  src/utils/buttonPresets.ts
  src/utils/multiMessage.ts
Labels: enhancement

#277 Guides
  .eslintignore
  .prettierignore
  guides/rules.md
  src/client.ts
  src/client/extraClient.ts
  src/commands/guide/autocomplete/name.ts
  src/commands/guide/index.ts
  src/commands/sendToAll.ts
  src/utils/guides.ts
Labels: bug, documentation, enhancement

#282 Quickstart
  buttonPresets.json
  guides/quickstart.md
  src/buttons/goToDM.ts
  src/client/extraClient.ts
  src/commands/guide/index.ts
  src/utils/buttonPresets.ts
  src/utils/sendQuickstart.ts
Labels: enhancement

#283 Add server rules guide
  .github/workflows/docs.yml
  docs/.npmignore
  docs/package-lock.json
  docs/package.json
  docs/src/.vuepress/config.ts
  docs/src/.vuepress/sidebar/commands.ts
  docs/src/.vuepress/sidebar/dev/dev.ts
  docs/src/.vuepress/sidebar/dev/self-host.ts
  docs/src/.vuepress/sidebar/quickstart.ts
  docs/src/.vuepress/sidebar/server.ts
  docs/src/.vuepress/styles/index.scss
  docs/src/about.md
  docs/src/bot-rules.md
  docs/src/commands/delete-auto.md
  docs/src/commands/generate-auto.md
  docs/src/commands/generate-once.md
  docs/src/commands/hsb-generate-auto.md
  docs/src/commands/index.md
  docs/src/commands/message-commands.md
  docs/src/commands/send-to-all.md
  docs/src/commands/set-auto.md
  docs/src/commands/set-device.md
  docs/src/commands/stats.md
  docs/src/commands/stop.md
  docs/src/commands/trigger-auto.md
  docs/src/dev/contribute.md
  docs/src/dev/index.md
  docs/src/dev/self-host/configuration/index.md
  docs/src/dev/self-host/index.md
  docs/src/dev/self-host/installation.md
  docs/src/dev/self-host/requirements.md
  docs/src/dev/self-host/v1-to-v2.md
  docs/src/index.md
  docs/src/quickstart/auto-screening.md
  docs/src/quickstart/index.md
  docs/src/quickstart/invite-bot.md
  docs/src/quickstart/join-server.md
  docs/src/quickstart/running-commands.md
  docs/src/server/fun-bots.md
  docs/src/server/index.md
  docs/src/server/roles.md
  docs/src/server/rules.md
  docs/src/server/school-specific.md
  docs/src/server/starboard.md
  docs/src/server/suggestions.md
  guides/server_rules.md
  src/client/extraClient.ts
Labels: documentation, enhancement

#284 More guides
  guides/contributing_a_guide.md
  guides/guides.md
  guides/post_set_auto.md
  guides/whats_new_version_2_1.md
  guides/whats_new_version_2_4.md
  src/client/extraClient.ts
  src/commands/guide/autocomplete/name.ts
  src/commands/setAuto.ts
  src/screeningClient/index.ts
  src/utils/guides.ts
Labels: documentation

#285 Version bump
  package.json
Labels: version change

#288 Change algorithim to floor so it always starts at multiple of 5
  src/commands/setCommand/autocomplete/minute.ts
Labels: bug

#289 Fancy badges
  README.md
Labels: documentation

#291 Update extraClient.ts
  src/client/extraClient.ts
Labels: bug

#294 Fix unique constraint error
  src/commands/setAuto.ts
  src/utils/logError/index.ts
  src/utils/logError/supplementors/sequelizeValidationError.ts
Labels: bug, enhancement

#295 Ephemeral by default
  src/commands/error/log/view/index.ts
  src/commands/error/view.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/profile.ts
  src/commands/setAuto.ts
  src/commands/setCommand/index.ts
  src/commands/testScreening.ts
Labels: enhancement

#296 Version bump
  package.json
Labels: version change

#298 Move post_set_auto to be sent in user DM
  src/commands/setAuto.ts
Labels: bug

#301 Make error post ephemeral by default
  src/commands/error/post.ts
Labels: enhancement

#302 Ignore custom collector buttons
  src/client/interactions/messageComponentInteraction.ts
Labels: bug

#303 Update extraClient.ts
  src/client/extraClient.ts
Labels: documentation

#305 Update ignore list to ignore guild member timeout
  errorLogIgnore.json
Labels: bug

#306 Have deferReply respect ephemerality
  src/screeningClient/index.ts
Labels: bug

#307 Set onEnd function for paginator
  src/utils/paginator.ts
Labels: bug

#310 Add walkthrough guide
  guides/device_list.md
  guides/walkthrough/page_1.md
  guides/walkthrough/page_2.md
  guides/walkthrough/page_3.md
Labels: documentation

#314 Refactor guides
  guides/guides.md
  guides/walkthrough/page_1.md
  guides/walkthrough/page_2.md
  guides/walkthrough/page_3.md
  package.json
  scripts/generateGuides.ts
  src/client/extraClient.ts
  src/commands/guide/custom/sendQuickstart.ts
  src/commands/guide/index.ts
  src/commands/sendToAll.ts
  src/commands/setAuto.ts
  src/data/buttonPresets.json
  src/data/errorLogIgnore.json
  src/data/guideData.json
  src/data/holidays.json
  src/utils/buttonPresets.ts
  src/utils/getHolidays.ts
  src/utils/guides.ts
  src/utils/logError/ignoreError.ts
Labels: documentation, enhancement

#315 Add some changelogs and refactor a bit
  guides/changelog/2_1.md
  guides/changelog/2_4.md
  guides/changelog/2_4_1.md
  guides/changelog/2_5.md
  guides/post_set_auto.md
  package.json
  src/data/guideData.json
Labels: documentation, enhancement

#317 Workflows only run when `.ts` files change
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
Labels: enhancement

#316 Add underline to False
  guides/walkthrough/page_2.md
Labels: documentation

#319 Exception for package(-lock).json
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
Labels: enhancement

#320 Prettier
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .prettierignore
Labels: bug

#321 Fix lint path ignores
  .github/workflows/lint.yml
Labels: enhancement

#323 Use concurrent-priority-worker-queue package.
  package-lock.json
  package.json
  src/client/extraClient.ts
  src/screeningClient/index.ts
  src/utils/workerQueue.ts
Labels: dependencies

#324 Change string boundaries to skip custom components.
  src/client/interactions/messageComponentInteraction.ts
Labels: bug

#325 Make owner message ephemeral
  package.json
  src/utils/checkOwner.ts
Labels: enhancement

#335 Make unique mode for error log
  package.json
  src/commands/error/log/view/index.ts
  src/commands/error/post.ts
  src/commands/error/view.ts
  src/commands/generateAuto.ts
  src/commands/generateOnce.ts
  src/commands/guide/index.ts
  src/commands/profile.ts
  src/commands/setAuto.ts
  src/commands/setCommand/index.ts
  src/commands/testScreening.ts
  src/commands/triggerAutoNow.ts
  src/utils/logError/index.ts
Labels: bug, enhancement

#338 Enhance error view
  src/commands/error/view.ts
Labels: enhancement

#336 Use a private variable to track ephemeral-ness since it doesn't work otherwise
  src/utils/paginator.ts
Labels: bug

#343 Auto gpl
  package-lock.json
  package.json
  scripts/automaticallyAddGPLToCode.ts
  scripts/generateGuides.ts
  scripts/updateAutoMigration.ts
  src/buttons/delete.ts
  src/buttons/goToDM.ts
  src/client/command.ts
  src/client/doGuildMemberCacheUpdate.ts
  src/client/interactions/commandInteraction.ts
  src/client/interactions/commandInteractionAutocomplete.ts
  src/client/interactions/messageComponentInteraction.ts
  src/commands/error/log/index.ts
  src/commands/error/log/view/autocomplete/after.ts
  src/commands/error/log/view/autocomplete/afterTime.ts
  src/commands/error/log/view/autocomplete/before.ts
  src/commands/error/log/view/autocomplete/beforeTime.ts
  src/commands/error/log/view/autocomplete/typeStartsWith.ts
  src/commands/error/log/view/index.ts
  src/commands/guide/autocomplete/name.ts
  src/commands/guide/custom/sendQuickstart.ts
  src/commands/setCommand/autocomplete/devices.ts
  src/commands/setCommand/autocomplete/minute.ts
  src/orm/migrations/makeMigrationExport.ts
  src/utils/buttonPresets.ts
  src/utils/createOrUpdate.ts
  src/utils/customCollector.ts
  src/utils/formatErrorLogEntry.ts
  src/utils/generateNumberChoicesInRange.ts
  src/utils/getHolidays.ts
  src/utils/guides.ts
  src/utils/logError/ignoreError.ts
  src/utils/logError/runAndLog.ts
  src/utils/logError/serializeInteraction.ts
  src/utils/logError/serializeMessageComponentInteraction.ts
  src/utils/logError/supplementors/sequelizeValidationError.ts
  src/utils/paginator.ts
  src/utils/postToGithub.ts
Labels: documentation

#346 Error log prune
  src/commands/error/delete.ts
  src/commands/error/index.ts
  src/commands/error/log/index.ts
  src/commands/error/log/prune/index.ts
  src/commands/error/view.ts
Labels: enhancement

#347 Fix empty array check
  src/commands/error/log/view/index.ts
Labels: bug

#348 Add test_screening documentation
  guides/walkthrough/page_2.md
Labels: documentation

#352 Deprecate `hsb/` text commands
  src/client/extraClient.ts
Labels: enhancement

#369 Interactive set command
  src/client.ts
  src/commands/profile.ts
  src/commands/setCommand/index.ts
  src/commands/setCommand/setMenu.ts
  src/data/devicesInSelect.json
  src/discordjs-overrides.d.ts
  src/screeningClient/getUserInfo/getAutoData.ts
  src/screeningClient/getUserInfo/getAutoDayData.ts
  src/screeningClient/getUserInfo/getDeviceData.ts
  src/screeningClient/index.ts
  src/screeningClient/processScreening/generateAndSendScreenshot.ts
  src/utils/createOrUpdate.ts
  src/utils/customCollector.ts
  src/utils/paginator.ts
Labels: bug, enhancement

#370 Fix dependabot errors
  package-lock.json
  package.json
Labels: dependencies

#371 Use new object syntax
  src/commands/stats.ts
  src/commands/testScreening.ts
Labels: bug

#372 Add doc changes
  guides/changelog/2_6.md
  guides/walkthrough/page_2.md
  src/data/guideData.json
Labels: documentation

#373 Forgot to remove -dev
  package.json
Labels: bug

#374 Update 2_5.md
  guides/changelog/2_5.md
Labels: documentation

#375 Update 2_6.md
  guides/changelog/2_6.md
Labels: documentation

#376 Fix version number in message
  guides/changelog/2_6.md
Labels: documentation

#390 Add Issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#391 Use `process.on()` to handle signals
  src/client.ts
Labels: enhancement

#392 Use object for `setFooter()`
  src/utils/paginator.ts
Labels: enhancement

#393 Use eslint instead of lint
  .github/workflows/lint.yml
  package.json
Labels: enhancement

#394 Profile time enhancements
  src/commands/profile.ts
  src/commands/setCommand/setMenu.ts
Labels: enhancement

#395 Add paginator code
  src/commands/testScreening.ts
Labels: enhancement

#397 Import from timers
  src/client.ts
  src/client/doAutoLoop.ts
  src/client/doGuildMemberCacheUpdate.ts
Labels: enhancement

#398 Remove usage for quickstart
  README.md
Labels: documentation

#399 Remove all functionality requiring members.
  src/client/autoAssignSchoolRole.ts
  src/client/doAutoLoop.ts
  src/client/doGuildMemberCacheUpdate.ts
  src/client/extraClient.ts
  src/commands/sendToAll.ts
  src/commands/testScreening.ts
  src/commands/triggerAutoNow.ts
  src/screeningClient/interfaces.ts
  src/utils/getValidUserIDs.ts
Labels: enhancement

#400 Version bump, add changelog and update guides
  guides/changelog/2_7.md
  guides/guides.md
  package.json
  src/data/guideData.json
Labels: documentation, version change

#402 Return on onEnd() if single page
  src/utils/paginator.ts
Labels: bug

#405 Add reset command
  src/client/extraClient.ts
  src/commands/reset.ts
Labels: enhancement

#406 Add !== null checks
  src/commands/setCommand/index.ts
Labels: bug

#415 2.8.0: Features, bug fixes and changelog
  guides/changelog/2_8.md
  guides/walkthrough/page_2.md
  guides/walkthrough/page_3.md
  guides/walkthrough/page_4.md
  package.json
  src/commands/error/post.ts
  src/commands/reset.ts
  src/commands/stats.ts
  src/commands/testScreening.ts
  src/data/guideData.json
Labels: enhancement, version change

#419 Change signal and destroy client
  src/client.ts
Labels: bug

#420 Minor version bump
  package.json
Labels: version change
